configuration: Release

before_build:
  - nuget restore
  - '"C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 Tools/sn.exe" -Vr ./src/ADAL.PCL/bin/Release/Microsoft.IdentityModel.Clients.ActiveDirectory.dll'

skip_commits:
  files:
    - '**/*.md'
    - 'changelog.txt'

on_finish:
# Uncomment this to be able to RDP into the build agent
# ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))